name: Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-python@v2

    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Build and Commit
      uses: sphinx-notes/pages@v2

    - name: Install dependencies
      run: |
        python -m pip install sphinx
        python -m pip install sphinx-rtd-theme

    - name: Make sphinx docs
      run: |
        make -C docs html

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_SECRET }}
        branch: gh-pages
        force: true
        directory: ./docs/build/html
