name: Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master
      with:
        ref: ${{ github.head_ref }}
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install sphinx-rtd-theme

    - name: Make html documentation
      run: |
        cd docs
        make html
        ls -la build
        cd ..

    - name: Commit files
      run: |
        cd docs/build/html
        git init
        touch .nojekll
        git add .
        git config --global user.email "aarekuha@gmail.com"
        git config --global user.name "github-actions[bot]"
        git commit -a -m "Make actual docs"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_SECRET }}
        branch: gh-pages
        force: true
        directory: ./docs/build/html
