name: Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master
      with:
        ref: ${{ github.head_ref }}
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    - name: Commit files
      run: |
        sudo mkdir -p /tmp/docs
        sudo chown -R $USER:$USER /tmp/docs
        sudo mv docs/build/html/* /tmp/docs
        sudo rm -rf *
        sudo mv /tmp/docs/* .
        touch .nojekll
        git add .
        git config --global user.email "aarekuha@gmail.com"
        git config --global user.name "github-actions[bot]"
        git commit -a -m "Add changes"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_SECRET }}
        branch: gh-pages
        force: true
